# Generated by Django 4.2.2 on 2023-08-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktorius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas_pavarde', models.CharField(max_length=100, verbose_name='Vardas pavarde')),
                ('g_metai', models.IntegerField(verbose_name='Gimimo data')),
                ('kinografija', models.TextField(default='', max_length=2000, verbose_name='Kino')),
            ],
        ),
        migrations.CreateModel(
            name='Filmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('rodymo_data', models.IntegerField(verbose_name='Kada pasirode')),
                ('aprasymas', models.TextField(max_length=2000, verbose_name='Aprasymas')),
                ('aktoriusFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmas_set', to='filmai.aktorius')),
            ],
        ),
    ]
